apiVersion: v1
kind: Service
metadata:
  name: crypto-x
spec:
  type: NodePort
  selector:
    app: crypto-x-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
