name: CI/CD Pipeline for Crypto-X

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: udithdev/crypto-x:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Configure kubectl
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG }}
        run: echo "$KUBECONFIG_CONTENT" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          ls
          kubectl apply -f deployment-blue.yaml
          kubectl apply -f deployment-green.yaml
          kubectl apply -f service.yaml
          kubectl rollout status deployment/crypto-x-blue
          kubectl rollout status deployment/crypto-x-green
